### ISSUE TITLE
Adding Own Experiment_ID or ObjectID Inside Database

### ISSUE THREAD

**Issue by dendisuhubdy** [mila-udem/orion#105]
So we had a use case where we needed to save the Tensorboard logs and model checkpoints inside a folder where we control the naming of it. Like

```
exp_id = uuid.uuid4().__str__()
```

Currently, if I'm not wrong it's set here automatically`https://github.com/mila-udem/orion/blob/6219add391aec50b1714a2d6f5910c5f6530310e/src/orion/core/worker/experiment.py#L124` 

How can we pass it via the command line interface instead?

**Comment by bouthilx** [comment]
Do you only want a specific folder per experiment, or a hierarchy like this
```
/experiment-folder
    /trial-1
    /trial-2
```

**Comment by dendisuhubdy** [comment]
I decided to pass it via the results list to orion.client.
