### ISSUE TITLE
Concatenate user defined name and generated by Orion

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [mila-udem/orion#118]
As in (or similar syntax)
```
--model-name~model_'trial.has_name'
```

**Comment by tsirif** [comment]
Current regex will parse out the `model_'trial.hash_name'`. Perhaps adding another one like `[A-Za-z_]*'(.*)'` will do the job. However I am not sure how easy it will be now to disentagle the possible cases that come after marker `~`.

@dmitriy-serdyuk Can you describe a case where this feature is going to be useful or convenient? Why is it needed?

**Comment by dmitriy-serdyuk** [comment]
I want to give my experiment a human-readable name. I could use this name to generate pretty plots, for example. But I still need different names to save checkpoints separately for each model.

Maybe you can provide a function `cat("model_", trial.hash_name)` or an operator `"model_" + trial.hash_name`? I don't know much about internals of Orion, but it seems that it is a mini language already with functions and variables.

**Comment by bouthilx** [comment]
I would rather use templates. Something like ```--model-name model_{trial.has_name}```. We shouldn't need the ```~``` sign other than for dimensions.

**Comment by bouthilx** [comment]
@tsirif If you agree with the solution using templates we could close this issue.

**Comment by tsirif** [comment]
Yes I agree!

**Comment by bouthilx** [comment]
See #119
