### ISSUE TITLE
AbstractDB: Add option to fetch/act-on most recent documents

### ISSUE THREAD

**Issue by tsirif** [mila-udem/orion#15]
Perhaps it will be useful in the future to have an option in database interface for returning or acting-on only the **most recent matched documents**.

An attempt lies at tsirif@cda014b, on branch [`feature/db/most_recent`](https://github.com/tsirif/metaopt/tree/feature/db/most_recent).

**Comment by bouthilx** [comment]
Dead-link. Issue can be found with search keywords if needed.
