### ISSUE TITLE
Resolve possible configuration instantiation & extraction cases

### ISSUE THREAD

**Issue by tsirif** [mila-udem/orion#32]
Out of the possible things that can be given through metaopt configuration procedure, the final configuration dictionary is going to have keys which correspond to **existing `Experiment` entities** and keys which correspond to **`AbstractAlgorithm` instances**.

Instantiation
-----------------

An **algorithm** can be described as:
- [ ] YAML constructor tags (search for section `Constructors, representers, resolvers` in [this](http://pyyaml.org/wiki/PyYAMLDocumentation))
- [x] Through `metaopt.utils.Factory` interface using a algorithm implementation identifier (like class name). This one will search for an implementation to instantiate using two mechanisms:
   - [x] For internal APIs: Searching for subclasses of the base class, which are implemented in modules that exist in the same directory as it. We might consider to change it later to import all modules in a certain package. This works properly as it is tested.
   - [x] For external APIs: Use `pkg_resources` [entry points](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points) to select a registered interface (from a metaopt.algo extension) and check whether it is a proper subclass of the base class.

All of these ways must be finally resolved by `Experiment._sanitize_config`, which will instantiate and validate any objects that can be inferred from the configuration. It should not expect that all values in the `nesteddict` will correspond to numericals, dicts, or class identifiers. It may be also objects instantiated immediately by YAML itself; in this case it should check whether they are truly instances of what they are supposed to be.

However, as we agreed in nested algorithm configurations (instead of dicts), I will have to create a way to recognize and instantiate recursively `AbstractAlgorithm` objects from within `AbstractAlgorithm.__init__`, using checks where it is appropriate and `metaopt.utils.Factory`. This in turn kinda implies that all parameters expected by an implementation (as they can be different among implementations and as we want to minimize code repetitions or requirements for people implementing extensions) must be somehow exported from the inherited class to the base one. This can be done by using class variables [e.g. `cls.params` for name declaration, `cls.defaults` for their defaults, `cls.paramtypes` for their types (optional), `cls.description` for documentation (to enhance `cls.__doc__` with parameter documentation)]; I am not considering `cls.__slots__` here as many algorithms must hold an internal state in order to be functional. A decorator can be exported from `metaopt.algo.base` that can facilitate declaring new parameters.

For an **experiment**, we should discuss how the values. All that it takes for a primary key of an experiment is the pair **(name, user)**. So, this definitely will specify one Experiment and should be part of when specifying a referent experiment. 

Extraction
--------------

I propose that every implementation of algorithm should have a mechanism (general `configuration` property) that creates the settings of an `AbstractAlgorithm` object in a dictionary form. This will serve 2 different purposes:

1. Automatic post installation hooks (an executable to be defined in metaopt.core package) can create example configuration files for any possible metaopt.algo extension.
2. Call within `Experiment.configuration` to serve a experiment's settings in dict form.

A little note to be taken here is that `AbstractAlgorithm.configuration` must recognize if some attributes or values are `AbstractAlgorithm` instances and recursively call it. This is because: (a) convenient since algorithm objects can decorate themselves with other instances, (b) we agreed that an algorithm's complete specification in experiment's settings should be in dictionary form.

**Comment by bouthilx** [comment]
I believe this is resolved with current implementation of ```Factory``` and its improvements currently being implemented by @DatCorno
