### ISSUE TITLE
TODO: Transformation of Dimension objects and Spaces

### ISSUE THREAD

**Issue by tsirif** [mila-udem/orion#40]
Reasonale: Some algorithms operate only on ordered spaces, some others only on real spaces. So defined algorithms should have a class "property" to declare their own requirements on the parameter domain they are able to operate on. In response, `metaopt.core` should define and implement `Transformer` classes, which will be able to decorate `Dimension` objects. `metaopt.core.worker.primary_algo` implements the wrapper class which will poll the `algorithm` attribute for `requests` and will wrap the dimensions in given `space` object during `__init__` to fulfill them. Then, a space will be constructed with the transformed dimensions and this will be set to the algorithms. The original space is reserved.

This proposal is made having in mind that transformers' existence and functionality should be "hidden" from `Experiment` class and also `BaseAlgorithm` implementation. For `Experiment`'s and `Producer`'s side this is done by the existence of `PrimaryAlgo` class. For `BaseAlgorithm`'s this is done by providing an agnostic interface through the `Space` object.

**Comment by bouthilx** [comment]
Implemented in #60
