### ISSUE TITLE
Visualization of Experiments Related to Hyperparameters 

### ISSUE THREAD

**Issue by dendisuhubdy** [mila-udem/orion#73]
Graph 1 
![screenshot from 2018-05-10 13-47-57](https://user-images.githubusercontent.com/4477337/39885092-c33a1852-5459-11e8-920f-63398d4f8637.png)
Graph 2 
![screenshot from 2018-05-10 13-48-04](https://user-images.githubusercontent.com/4477337/39885093-c3530b82-5459-11e8-92f7-9780db0101e9.png)
Graph 3 
![screenshot from 2018-05-10 13-48-10](https://user-images.githubusercontent.com/4477337/39885094-c374798e-5459-11e8-9576-741049440dbe.png)
Graph 4 
![screenshot from 2018-05-10 13-48-19](https://user-images.githubusercontent.com/4477337/39885095-c38bcca6-5459-11e8-8dfc-e7aaba0bc4b2.png)
Graph 5 
![screenshot from 2018-05-10 13-48-26](https://user-images.githubusercontent.com/4477337/39885096-c39d779e-5459-11e8-91ef-62b38e76d3e0.png)
Graph 6 
![screenshot from 2018-05-10 13-48-31](https://user-images.githubusercontent.com/4477337/39885097-c3b3f5c8-5459-11e8-8d34-8861b4644803.png)
Graph 7 
![screenshot from 2018-05-10 13-49-15](https://user-images.githubusercontent.com/4477337/39885098-c3c4ff1c-5459-11e8-94a1-f33fc3ca2940.png)
Graph 8 
![screenshot from 2018-05-10 13-49-22](https://user-images.githubusercontent.com/4477337/39885099-c3d97a5a-5459-11e8-83f1-d3768e361583.png)
Graph 9 
![screenshot from 2018-05-10 13-49-33](https://user-images.githubusercontent.com/4477337/39885100-c3f1d262-5459-11e8-849e-8c01e1b16a80.png)
Graph 10 
![screenshot from 2018-05-10 13-49-41](https://user-images.githubusercontent.com/4477337/39885101-c40a085a-5459-11e8-8e90-792a44b343bb.png)
Graph 11 
![screenshot from 2018-05-10 13-53-07](https://user-images.githubusercontent.com/4477337/39885103-c41dc552-5459-11e8-97b3-67604d126956.png)

**Comment by bouthilx** [comment]
Cool! @dendisuhubdy Could you please list the references with the graphs?

**Comment by dendisuhubdy** [comment]
@bouthilx bout to do  just dat
