### ISSUE TITLE
Default value should be a slotted attribute of `Trial.Param`

### ISSUE THREAD

**Issue by tsirif** [mila-udem/orion#88]
Copying discussion from #83 

> T:
> Q: Is the default value part of `Trial.Param`?
> X:
> Well, a `Trial.Param` instance is basically a `dimension.sample()` turned into a param. So, if we have a default value, `Trial.Param` is a very convenient and natural way to encapsulate such default value. Furthermore, for `DimensionAddition` and `DimensionDeletion` we need to add a `Trial.Param` object to each trials, so using such encapsulation for default value is very very convenient.
> T:
> I agree. This means that default_value should be a slotted attribute of `Trial.Param`?

**Comment by bouthilx** [comment]
I don't think it should. The default_value is encapsulated as the value of Trial.Param. You could have either

Trial.Param(dimension.name, dimension.type, dimension.sample())
or

Trial.Param(dimension.name, dimension.type, dimension.default_value)
We don't need to know if it was sampled or if it is the default value. It simply is the value of the param.
