### ISSUE TITLE
`Trial.Param` should be hashable

### ISSUE THREAD

**Issue by tsirif** [mila-udem/orion#89]
Copying discussion from #83 

> T:
> This should have been done earlier. It is useful fo the `hash_name` property as well. Shall I right a `__hash__` and change the implementation of the `hash_name`? I think I should. This will be in a future PR.
> X:
> Yes sure if there is hashing that is certainly related to `__eq__`.

The reason is that in #69, a unique string identifier per trial may be requested from the user to disambiguate among temporary local disk resource locations that may be used for resumability or logging. Implementation of `Trial.hash_name` is suboptimal.

**Comment by bouthilx** [comment]
Done in #103
