### ISSUE TITLE
Comparison of Dimensions with same prior's name but different parameters returns True

### ISSUE THREAD

**Issue by DatCorno** [mila-udem/orion#90]
Let A and B be two instances of the Dimension class defined as follow :

Name | Type | Prior
-------- | ------- | ------
x | Real | uniform(0, 10)
x | Real | uniform(0,1)

While it is evident that these two Dimensions are not equal (since they do not allow values on the same interval), the current `__eq__` function for Dimension comparison returns True. This comes from the fact that the DimensionBuilder uses the expression passed through the command line (or a config file), for example, `-x~uniform(0,10)`, and passes it through an `eval` call which uses the values inside the parenthesis as arguments to the function related to that distribution.
Unfortunately, this operation does not preserve the `expression` string.

**Comment by bouthilx** [comment]
Fixed in #114
